### ISSUE TITLE
Bug: Publishing assets in a config-less Sage 10 go into vendor

### ISSUE THREAD

**Issue by Log1x** [roots/acorn#161]
### Steps To Reproduce

1. Install latest Sage 10 dev-main
2. `composer require log1x/poet`
3. `wp acorn vendor:publish --provider="Log1x\Poet\PoetServiceProvider"`

### Expected Behavior

Acorn creates a `config` folder inside of Sage and publishes the config there.

### Actual Behavior

The config gets published into `vendor/roots/acorn/config`

### Relevant Log Output

```shell
~/Sites/sage/web/app/themes/sage
❯ wp acorn vendor:publish --provider="Log1x\Poet\PoetServiceProvider"
Copied File [/vendor/log1x/poet/config/poet.php] To [/Users/brandon/Development/projects/acorn/config/poet.php]
Publishing complete.
```

### Versions

dev-main

**Comment by Log1x** [comment]
Manually creating a `config` folder and placing `poet.php` inside of it results in:

```php
Fatal error: Uncaught Exception: Unable to load the "app" configuration file. in /Users/brandon/Development/projects/acorn/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:68 Stack trace: #0 /Users/brandon/Development/projects/acorn/src/Roots/Acorn/Bootstrap/LoadConfiguration.php(36): Illuminate\Foundation\Bootstrap\LoadConfiguration->loadConfigurationFiles(Object(Roots\Acorn\Application), Object(Illuminate\Config\Repository)) #1 /Users/brandon/Development/projects/acorn/src/Illuminate/Foundation/Application.php(237): Roots\Acorn\Bootstrap\LoadConfiguration->bootstrap(Object(Roots\Acorn\Application)) #2 /Users/brandon/Development/projects/acorn/src/Roots/Acorn/Bootloader.php(208): Illuminate\Foundation\Application->bootstrapWith(Array) #3 /Users/brandon/Development/projects/acorn/src/Roots/Acorn/Bootloader.php(181): Roots\Acorn\Bootloader->app() #4 /Users/brandon/Sites/sage/web/wp/wp-includes/class-wp-hook.php(303): Roots\Acorn\Bootloader->__invoke('') #5 /Users/brandon/Sites/sage/web/wp/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #6 /Users/brandon/Sites/sage/web/wp/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #7 /Users/brandon/Sites/sage/web/wp/wp-settings.php(556): do_action('after_setup_the...') #8 /Users/brandon/Sites/sage/web/wp-config.php(9): require_once('/Users/brandon/...') #9 /Users/brandon/Sites/sage/web/wp/wp-load.php(55): require_once('/Users/brandon/...') #10 /Users/brandon/Sites/sage/web/wp/wp-admin/admin.php(34): require_once('/Users/brandon/...') #11 /Users/brandon/Sites/sage/web/wp/wp-admin/plugins.php(10): require_once('/Users/brandon/...') #12 /Users/brandon/.composer/vendor/laravel/valet/server.php(235): require('/Users/brandon/...') #13 {main} thrown in /Users/brandon/Development/projects/acorn/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 68
```

**Comment by purplefeel** [comment]
Hi! Is this going to be fixed any soon?

**Comment by retlehs** [comment]
this is considered a high priority bug on our end, but remember that you're choosing to use beta versions of an open source project. there's bound to be some bugs while we iron out new functionality.

i'd suggest using a different version of acorn/sage that doesn't conflict with your workflow if you're in immediate need of a fix for this bug. this feature was recently added to both acorn and sage — there's not even a release of sage that's using this feature rn.

thanks for your patience

**Comment by QWp6t** [comment]
This is fixed on the main branch right now. x-ref #172

> Manually creating a config folder and placing poet.php inside of it...

This also works. x-ref #167
