### ISSUE TITLE
Bug: ExceptionHandler throws critical error in CLI while on production

### ISSUE THREAD

**Issue by Log1x** [roots/acorn#162]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Description

N/A

### Steps To Reproduce

1. Use latest Acorn and Sage 10
2. Set your environment to `production`
3. Run a command that would throw an error: `wp acorn vendor:publish X`

### Expected Behavior

![Screenshot](https://i.imgur.com/lCXAr04.png)

### Actual Behavior

![Screenshot](https://i.imgur.com/82PJaM9.png)

### Relevant Log Output

```shell
~/Sites/sage/web/app/themes/sage
❯ wp acorn vendor:publish X
Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php:1093
Stack trace:
#0 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php(886): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/brandon/Development/projects/acorn/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#3 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php(694): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#4 /Users/brandon/Development/projects/acorn/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#5 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php(1423): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#6 /Users/brandon/Development/projects/acorn/src/Illuminate/Foundation/Console/Kernel.php(366): Illuminate\Container\Container->offsetGet('Illuminate\\Cont...')
#7 /Users/brandon/Development/projects/acorn/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Foundation\Console\Kernel->reportException(Object(Symfony\Component\Console\Exception\RuntimeException))
#8 /Users/brandon/Development/projects/acorn/src/Roots/Acorn/Bootstrap/RegisterConsole.php(52): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 [internal function]: Roots\Acorn\Bootstrap\RegisterConsole->Roots\Acorn\Bootstrap\{closure}(Array, Array)
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(102): call_user_func(Object(Closure), Array, Array)
#11 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func(Object(Closure), Array, Array)
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(399): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(422): WP_CLI\Runner->run_command(Array, Array)
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1194): WP_CLI\Runner->run_command_and_exit()
#16 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#17 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(77): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#18 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#19 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#20 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#21 {main}
  thrown in /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php on line 1093
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.
```

### Versions

dev-main

**Comment by QWp6t** [comment]
This is fixed in #169

![image](https://user-images.githubusercontent.com/2104321/152663043-d28e7de1-a079-40d9-b369-4a715c1fe3d8.png)
