### ISSUE TITLE
Bug: Acorn requires /resources to exist in theme

### ISSUE THREAD

**Issue by intelligence** [roots/acorn#216]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Using Acorn with a theme that does not have a folder named `/resources` causes a fatal error.

I'm using Bedrock with Acorn (with ACF Composer and Poet) to create a theme that's to be used for headless WordPress. As there won't be any frontend, `/resources` seems superfluous.

#### Temporary workarounds
Adding a folder named `/resources` 

### Steps To Reproduce

1. `composer require roots/acorn` in Bedrock
2. Add https://github.com/roots/sage/blob/main/functions.php#L32 in `functions.php`
3. Fatal error occurs if `/resources` is missing in theme folder

### Expected Behavior

`/resources` should be optional

### Actual Behavior

Is not optional

### Relevant Log Output

```shell
`Fatal error: Uncaught Exception: The /srv/www/domain.tld/current/vendor/roots/acorn/resources directory must be present. in /srv/www/domain.tld/current/vendor/roots/acorn/src/Roots/Acorn/Application.php:126 Stack trace: #0 /srv/www/domain.tld/current/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(206): Roots\Acorn\Application->usePaths(Array) #1 /srv/www/domain.tld/current/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(181): Roots\Acorn\Bootloader->app() #2 /srv/www/domain.tld/current/web/wp/wp-includes/class-wp-hook.php(307): Roots\Acorn\Bootloader->__invoke('') #3 /srv/www/domain.tld/current/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #4 /srv/www/domain.tld/current/web/wp/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #5 /srv/www/domain.tld/current/web/wp/wp-settings.php(565): do_action('after_setup_the...') #6 /srv/www/domain.tld/current/web/wp-config.php(9): require_once('/srv/www/dev.in...') #7 /srv/www/domain.tld/current/web/wp/wp-load.php(55): require_once('/srv/www/dev.in...') #8 /srv/www/domain.tld/current/web/wp/wp-blog-header.php(13): require_once('/srv/www/dev.in...') #9 /srv/www/domain.tld/current/web/index.php(6): require('/srv/www/dev.in...') #10 {main} thrown in /srv/www/domain.tld/current/vendor/roots/acorn/src/Roots/Acorn/Application.php on line 126`
```

### Versions

2.0.4

**Comment by intelligence** [comment]
Closed by 8b73a59
