### ISSUE TITLE
Bug: Undefined array key "dependencies" 

### ISSUE THREAD

**Issue by LucasDemea** [roots/acorn#257]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Description

In a trellis + bedrock + sage setup, when I try to scrape my website with criticalCSS imported in my bud config, The following exception gets thrown:
```console
Undefined array key "dependencies" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"dependencies\" at /srv/www/site/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Assets/Bundle.php:97)
```

My current workaround is:
```diff
//.../vendor/roots/acorn/src/Roots/Acorn/Assets/Bundle.php

public function dependencies()
{
-    return $this->bundle['dependencies'];
+    return $this->bundle['dependencies'] ?? [];
}
```

### Steps To Reproduce

run [critical-css-webpack-plugin](https://www.npmjs.com/package/critical-css-webpack-plugin)  on a sage theme.

### Expected Behavior

It should work.

### Actual Behavior

An ErrorException gets thrown

### Relevant Log Output

```shell
Undefined array key "dependencies" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"dependencies\" at /srv/www/site/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Assets/Bundle.php:97)
[stacktrace]
#0 /srv/www/site/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Bootstrap/HandleExceptions.php(54): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', '/srv/www/site...', 97, Array)
#1 /srv/www/site/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Assets/Bundle.php(97): Roots\\Acorn\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', '/srv/www/site...', 97)
#2 /srv/www/site/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Assets/Bundle.php(84): Roots\\Acorn\\Assets\\Bundle->dependencies()
#3 /srv/www/site/current/web/app/themes/sage/vendor/illuminate/collections/Traits/EnumeratesValues.php(245): Roots\\Acorn\\Assets\\Bundle->Roots\\Acorn\\Assets\\{closure}('js/575.bd247c.j...', 0)
#4 /srv/www/site/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Assets/Bundle.php(85): Illuminate\\Support\\Collection->each(Object(Closure))
#5 /srv/www/site/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Assets/Concerns/Enqueuable.php(72): Roots\\Acorn\\Assets\\Bundle->js(Object(Closure))
#6 /srv/www/site/current/web/app/themes/sage/vendor/roots/acorn/src/Roots/Acorn/Assets/Concerns/Enqueuable.php(84): Roots\\Acorn\\Assets\\Bundle->enqueueJs()
#7 /srv/www/site/current/web/app/themes/sage/app/setup.php(29): Roots\\Acorn\\Assets\\Bundle->enqueue()
#8 /srv/www/site/current/web/wp/wp-includes/class-wp-hook.php(307): App\\{closure}('')
#9 /srv/www/site/current/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#10 /srv/www/site/current/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#11 /srv/www/site/current/web/wp/wp-includes/script-loader.php(2156): do_action('wp_enqueue_scri...')
#12 /srv/www/site/current/web/wp/wp-includes/class-wp-hook.php(307): wp_enqueue_scripts('')
#13 /srv/www/site/current/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#14 /srv/www/site/current/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#15 /srv/www/site/current/web/wp/wp-includes/general-template.php(3042): do_action('wp_head')
#16 /srv/www/site/current/web/app/themes/sage/index.php(6): wp_head()
#17 /srv/www/site/current/web/wp/wp-includes/template-loader.php(106): include('/srv/www/site...')
#18 /srv/www/site/current/web/wp/wp-blog-header.php(19): require_once('/srv/www/site...')
#19 /srv/www/site/current/web/index.php(6): require('/srv/www/site...')
#20 {main}
"}
```

### Versions

2.1.2

**Comment by QWp6t** [comment]
Fixed in https://github.com/roots/acorn/commit/85d61f83673a71e8b56c10cbd0a3107626c08b93
