### ISSUE TITLE
Bug: singe upgrade to v3, WP Cli sends fatal error

### ISSUE THREAD

**Issue by bonakor** [roots/acorn#261]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Since I upgraded to V3, following the Upgrading Guide, whenever I try a WP-CLI command, I get this error: 
Next Illuminate\Contracts\Container\BindingResolutionException: Target class [blade.compiler] does not exist. in /myproject/vendor/illuminate/container/Container.php:895

### Steps To Reproduce

I'm using Sage V10 but one of the alpha version, on PHP 8.0

### Expected Behavior

Everything should be running smoothly

### Actual Behavior

It triggers a fatal error

### Relevant Log Output

```shell
``
Fatal error: Uncaught ReflectionException: Class "blade.compiler" does not exist in /sites/dev.tennismajors.com/files/tennismajors/vendor/illuminate/container/Container.php:893
Stack trace:
#0 /sites/dev.tennismajors.com/files/tennismajors/vendor/illuminate/container/Container.php(893): ReflectionClass->__construct()
#1 /sites/dev.tennismajors.com/files/tennismajors/vendor/illuminate/container/Container.php(774): Illuminate\Container\Container->build()
#2 /sites/dev.tennismajors.com/files/tennismajors/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(860): Illuminate\Container\Container->resolve()
#3 /sites/dev.tennismajors.com/files/tennismajors/vendor/illuminate/container/Container.php(710): Illuminate\Foundation\Application->resolve()
#4 /sites/dev.tennismajors.com/files/tennismajors/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(845): Illuminate\Container\Container->make()
#5 /sites/dev.tennismajors.com/files/tennismajors/vendor/roots/acorn/src/Illuminate/Foundation/helpers.php(120): Illuminate\Foundation\Application->make()
#6 /sites/dev.tennismajors.com/files/tennismajors/vendor/roots/acorn/src/Roots/helpers.php(108): app()
#7 /sites/dev.tennismajors.com/files/tennismajors/web/app/themes/tennis-majors-v2/vendor/log1x/sage-directives/src/Directives.php(90): Roots\app()
#8 /sites/dev.tennismajors.com/files/tennismajors/web/app/themes/tennis-majors-v2/vendor/log1x/sage-directives/src/Directives.php(35): Log1x\SageDirectives\Directives->blade()
#9 /sites/dev.tennismajors.com/files/tennismajors/web/wp/wp-includes/class-wp-hook.php(308): Log1x\SageDirectives\Directives->Log1x\SageDirectives\{closure}()
#10 /sites/dev.tennismajors.com/files/tennismajors/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#11 /sites/dev.tennismajors.com/files/tennismajors/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action()
#12 /sites/dev.tennismajors.com/files/tennismajors/web/wp/wp-settings.php(595): do_action()
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1317): require('...')
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1235): WP_CLI\Runner->load_wordpress()
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#16 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process()
#17 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#18 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#19 /usr/local/bin/wp(4): include('...')
#20 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [blade.compiler] does not exist. in /sites/dev.tennismajors.com/files/tennismajors/vendor/illuminate/container/Container.php:895
Stack trace:
#0 /sites/dev.tennismajors.com/files/tennismajors/vendor/illuminate/container/Container.php(774): Illuminate\Container\Container->build()
#1 /sites/dev.tennismajors.com/files/tennismajors/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(860): Illuminate\Container\Container->resolve()
#2 /sites/dev.tennismajors.com/files/tennismajors/vendor/illuminate/container/Container.php(710): Illuminate\Foundation\Application->resolve()
#3 /sites/dev.tennismajors.com/files/tennismajors/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(845): Illuminate\Container\Container->make()
#4 /sites/dev.tennismajors.com/files/tennismajors/vendor/roots/acorn/src/Illuminate/Foundation/helpers.php(120): Illuminate\Foundation\Application->make()
#5 /sites/dev.tennismajors.com/files/tennismajors/vendor/roots/acorn/src/Roots/helpers.php(108): app()
#6 /sites/dev.tennismajors.com/files/tennismajors/web/app/themes/tennis-majors-v2/vendor/log1x/sage-directives/src/Directives.php(90): Roots\app()
#7 /sites/dev.tennismajors.com/files/tennismajors/web/app/themes/tennis-majors-v2/vendor/log1x/sage-directives/src/Directives.php(35): Log1x\SageDirectives\Directives->blade()
#8 /sites/dev.tennismajors.com/files/tennismajors/web/wp/wp-includes/class-wp-hook.php(308): Log1x\SageDirectives\Directives->Log1x\SageDirectives\{closure}()
#9 /sites/dev.tennismajors.com/files/tennismajors/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#10 /sites/dev.tennismajors.com/files/tennismajors/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /sites/dev.tennismajors.com/files/tennismajors/web/wp/wp-settings.php(595): do_action()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1317): require('...')
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1235): WP_CLI\Runner->load_wordpress()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process()
#16 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#17 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#18 /usr/local/bin/wp(4): include('...')
#19 {main}
  thrown in /sites/dev.tennismajors.com/files/tennismajors/vendor/illuminate/container/Container.php on line 895``
```

### 10.0.0-beta.1: TBA

**Comment by retlehs** [comment]
This looks like a support request and not a bug so far 

In either case, [you will need to provide the actual steps required to reproduce your issue](https://discourse.roots.io/t/how-to-best-ask-questions-on-this-forum/24582) 

This is not a list of steps we can use to reproduce this error:

> using Sage V10 but one of the alpha version, on PHP 8.0

**Comment by bonakor** [comment]
All right. Will post tomorrow a support request. Thanks!

**Comment by retlehs** [comment]
https://github.com/Log1x/sage-directives/issues/77
