### ISSUE TITLE
Bug: `config()` and other helpers break CLI

### ISSUE THREAD

**Issue by Log1x** [roots/acorn#264]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

Using `config()` and other Laravel helpers that access the application container break CLI when used inside of a hook. This is a regression from Acorn v2 which worked as intended.

This is more than likely semi-related to #263 (although that appears to mainly affect `wp acorn optimize`).

#### What have you tried?

Changing hook priorities and changing the [`$bootstrappers`](https://github.com/roots/acorn/blob/main/src/Roots/Acorn/Console/Kernel.php#L44) order in the console Kernel.

#### What insights have you gained?

It's possible Acorn CLI is either booting later than it's supposed to or binding interfaces to the application container out of order.

#### Possible solutions

N/A

#### Temporary workarounds

N/A

### Steps To Reproduce

1. Add the following to `setup.php` or `filters.php`:

```php
add_filter('init', function () {
    echo config('app')['name'];
});
```

2. Refresh the frontend and see that the application name (defaults to Acorn) is echoed on the frontend.
3. Attempting to use `wp acorn` will throw an exception.

### Expected Behavior

Accessing the application container inside of hooks shouldn't break CLI.

### Actual Behavior

Accessing the application container inside of hooks break the CLI.

### Relevant Log Output

```shell
~/Sites/sage/web/app/themes/sage
❯ wp acorn
Fatal error: Uncaught ReflectionException: Class "config" does not exist in /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php:893
Stack trace:
#0 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php(893): ReflectionClass->__construct('config')
#1 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php(774): Illuminate\Container\Container->build('config')
#2 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(860): Illuminate\Container\Container->resolve('config', Array, true)
#3 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php(710): Illuminate\Foundation\Application->resolve('config', Array)
#4 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(845): Illuminate\Container\Container->make('config', Array)
#5 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/roots/acorn/src/Illuminate/Foundation/helpers.php(120): Illuminate\Foundation\Application->make('config', Array)
#6 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/roots/acorn/src/Illuminate/Foundation/helpers.php(276): app('config')
#7 /Users/brandon/Sites/sage/web/app/themes/sage/app/setup.php(21): config('app')
#8 /Users/brandon/Sites/sage/web/wp/wp-includes/class-wp-hook.php(307): App\{closure}('')
#9 /Users/brandon/Sites/sage/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#10 /Users/brandon/Sites/sage/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#11 /Users/brandon/Sites/sage/web/wp/wp-settings.php(598): do_action('init')
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1336): require('/Users/brandon/...')
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1254): WP_CLI\Runner->load_wordpress()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#16 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#17 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#18 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#19 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist. in /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php:895
Stack trace:
#0 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php(774): Illuminate\Container\Container->build('config')
#1 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(860): Illuminate\Container\Container->resolve('config', Array, true)
#2 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php(710): Illuminate\Foundation\Application->resolve('config', Array)
#3 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(845): Illuminate\Container\Container->make('config', Array)
#4 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/roots/acorn/src/Illuminate/Foundation/helpers.php(120): Illuminate\Foundation\Application->make('config', Array)
#5 /Users/brandon/Sites/sage/web/app/themes/sage/vendor/roots/acorn/src/Illuminate/Foundation/helpers.php(276): app('config')
#6 /Users/brandon/Sites/sage/web/app/themes/sage/app/setup.php(21): config('app')
#7 /Users/brandon/Sites/sage/web/wp/wp-includes/class-wp-hook.php(307): App\{closure}('')
#8 /Users/brandon/Sites/sage/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#9 /Users/brandon/Sites/sage/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#10 /Users/brandon/Sites/sage/web/wp/wp-settings.php(598): do_action('init')
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1336): require('/Users/brandon/...')
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1254): WP_CLI\Runner->load_wordpress()
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#16 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#17 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#18 {main}
  thrown in /Users/brandon/Sites/sage/web/app/themes/sage/vendor/illuminate/container/Container.php on line 895
```

### Versions

v3.0.0

**Comment by QWp6t** [comment]
fixed in #265 

fixed in latest release
